export const GET_DATASETS = "GET_DATASETS";
export const GET_DETECTORS = "GET_DETECTORS";
export const DELETE_PREPROCESSED_DATASET = "DELETE_PREPROCESSED_DATASET";
export const PREPROCESS = "PREPROCESS";
