export const GET_PREPOCESSED_DATASETS = "GET_PREPOCESSED_DATASETS";
export const GET_PREPOCESSED_DATASET = "GET_PREPOCESSED_DATASET";
export const POLLING_PREPROCESSED_DATASETS = "POLLING_PREPROCESSED_DATASETS";
export const POLLING_PREPROCESSED_DATASET = "POLLING_PREPROCESSED_DATASET";
export const GET_ANNOTATION = "GET_ANNOTATION";
export const UPDATE_ANNOTATION = "UPDATE_ANNOTATION";
